config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  get 'pictures/collection'
  root 'home#index'
  #root 'pictures#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
    has_one_attached :image
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :friends
        has_many :pictures
        validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    
    def configure_permitted_parameters
        added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def about
  end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    #@picture = Picture.new
    @picture = current_user.pictures.build
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    #@picture = Picture.new(picture_params)
    @picture = current_user.pictures.build(picture_params)
    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @picture = current_user.pictures.find_by(id: params[:id])
    redirect_to pictures_path, notice: "Not Authorized to Edit This Picture" if @picture.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:title, :caption, :image, :user_id, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  
  <br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
  <br/>

<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>
<%= link_to 'Show', @friend, class:"btn btn-secondary" %> | 
<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> | 
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/index.html.erb
<h1>Friends</h1>

<table class="table-striped table table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>User ID</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= friend.user_id %></td>
        <td><%= link_to 'Show', friend, class:"btn btn-outline-secondary btn-sm"%>
        <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/show.html.erb
<div class="bg-light container">
  <p>
    <strong>First name:</strong>
    <%= @friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= @friend.twitter %>
  </p>
</div>
<br/>
<%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %> |
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'The Pet Repository', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "About", home_about_path, class:"nav-link"%>
        </li>
      </ul>
      <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to "Your Pictures", pictures_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
              <%= link_to "Friends", friends_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
          </li>
        <% end %>
    </div>

  </div>
</nav>

app/views/home/about.html.erb
<h1> Welcome to The Pet Repository! 🐶 </h1>
<br/>
<p> This is a repository for your favorite pet pictures! </p>
<p> Browse our user submissions, or sign in and contribute your own! </p>

<div class="card" style="width: 45rem;">
  <div class="card-body">
    <h5 class="card-title">... Don't have any cute pet pictures to call your own? </h5>
    <p class="card-text">Don't worry! Click the link below to get your own unique machine generated dog pets! </p>
    <a href="https://xinxin001.github.io/ArtisticAnimalsWebApp/" target="_blank" class="btn btn-primary">The Artistic Animals Gallery</a>
  </div>
</div>
<br/>
<div class="card" style="width: 45rem;">
  <div class="card-body">
    <h5 class="card-title"> More on how I built this: </h5>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Personal Profile: 
            <a href="https://github.com/xinxin001/" target="_blank">GitHub</a> | 
            <a href="https://xinxin001.github.io/" target="_blank">Blog</a> 
        </li>
        <li class="list-group-item">
            The Pet Repository: <a href="https://github.com/xinxin001/ImageRepository" target="_blank">GitHub</a>
        </li>
        <li class="list-group-item">
            Artistic Animals: 
            <a href="https://github.com/xinxin001/ArtisticAnimals" target="_blank">GitHub</a> | 
            <a href="https://xinxin001.github.io/artisticanimals" target="_blank">Blog</a>
        </li>
    </ul>

  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  Welcome back <%= current_user.username %>!
<% else %>
  Sign up now to share your cute pet pictures to the world!
<% end %>
<h1>Global Repository</h1>

<table class="table-striped table table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Preview</th>
      <th>Title</th>
      <th>Caption</th>
      <th>Uploader</th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to image_tag(picture.image, style:"width:auto;  height:150px", class:"img-thumbnail img-fluid" ), picture %></td>
        <td><%= picture.title %></td>
        <td><%= picture.caption %></td>
        <td><%= picture.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Picture', new_picture_path, class:"btn btn-secondary" %>
<% else %>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Image Repository</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice%>
        <%= render 'layouts/alerts'%>
      <% end%>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :caption %>
    <%= form.text_area :caption, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :picture_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="field form-group">
    <%= form.text_field :username, id: :picture_username, class:"form-control", value:current_user.username, type: :hidden %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
  <br/>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture, class:'btn btn-secondary' %> |
<%= link_to 'Delete', @picture, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> | 
<%= link_to 'Back', pictures_path, class:'btn btn-dark' %>

app/views/pictures/index.html.erb
<h1><%= current_user.username %>'s Personal Repository</h1>

<table class="table-striped table table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Preview</th>
      <th>Title</th>
      <th>Caption</th>
      <th>Uploader</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <% if picture.user == current_user %>
      <tr>
        <td><%= link_to image_tag(picture.image, style:"width:auto;  height:150px", class:"img-thumbnail img-fluid" ), picture %></td>
        <td><%= picture.title %></td>
        <td><%= picture.caption %></td>
        <td><%= picture.username %></td>
        <td><%= link_to 'Delete', picture, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Picture', new_picture_path, class:"btn btn-secondary" %>
<% else %>
<% end %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<div class="card" style="width: 500px;">
  

  <div style="height:auto">
  <%= image_tag(@picture.image, style:'width:100%') %>
  </div>

  <div class="card-body">
    <h5 class="card-title">
      <strong>Title:</strong>
      <%= @picture.title %>
    </h5>
    <p class="card-text">
      <strong>Caption:</strong>
      <%= @picture.caption %>
    </p>
    <p class="card-text">
      <strong>Uploader:</strong>
      <%= @picture.username %>
    </p>
  </div>
  

 </div>
<br/>
<% if @picture.user == current_user %>
  <%= link_to 'Edit', edit_picture_path(@picture), class:"btn btn-secondary" %> |
<% end %>
<%= link_to 'Back', pictures_path, class:"btn btn-dark" %>